### PR TITLE
Implementation of `CacheProvider` and `SimpleDiskCache`. 

### PR DESCRIPTION
**Pull request by ethangreen-dev**
This introduces the `CacheProvider` abstract class, which provides a standardized set of cache manipulation functions that are used by compute delegates. 

In addition, `SimpleDiskCache` was implemented (and set as default within `DaskDelegateConfig`) to support simple disk-based caching workflows.

### CODE REVIEW

**Comment by ethangreen-dev** [comment]
@mdip226 When you run this make sure a directory is created where you spawned the Dask Cluster. It should contain file names with long MD5 hashes.

**Comment by mdip226** [comment]
are those just supposed to be parentheses? as in `type(CacheProvider)` ?
I'm still a little new to "python w/types"

**Comment by mdip226** [comment]
nevermind what I said, now I'm guessing its a new python feature

**Comment by ethangreen-dev** [comment]
Fixed the type error, it was caused by using Python 3.9 annotations without including `from __future__ import annotations`.

**Comment by mdip226** [comment]
Ah, gotcha. I'm still working on a way to be able to easily switch between python versions in my environment... it's a mess because I wasn't being organized when I installed them

**Comment by mdip226** [comment]
The server side looks o.k. up to the point it tries to plot
```
2021-11-21 14:42:59,010 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:42:59] "POST /api/v1/gillespy2/model/run HTTP/1.1" 201 -
2021-11-21 14:42:59,010 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:42:59] "POST /api/v1/gillespy2/model/run HTTP/1.1" 201 -
2021-11-21 14:42:59,015 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:42:59] "GET /api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status HTTP/1.1" 200 -
2021-11-21 14:42:59,015 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:42:59] "GET /api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status HTTP/1.1" 200 -
2021-11-21 14:43:04,023 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:43:04] "GET /api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status HTTP/1.1" 200 -
2021-11-21 14:43:04,023 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:43:04] "GET /api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status HTTP/1.1" 200 -
2021-11-21 14:43:04,028 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:43:04] "GET /api/v1/memory/bfb440ab3ba796a0f324193fc6f69194-run_1/plot HTTP/1.1" 404 -
2021-11-21 14:43:04,028 - werkzeug - INFO - 127.0.0.1 - - [21/Nov/2021 14:43:04] "GET /api/v1/memory/bfb440ab3ba796a0f324193fc6f69194-run_1/plot HTTP/1.1" 404 -
```

**Comment by mdip226** [comment]
this is the output in the notebook:
```
http://localhost:1234/api/v1/gillespy2/model/run
http://localhost:1234/api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status
The job is waiting for dependencies to arrive in memory.
0
http://localhost:1234/api/v1/job/bfb440ab3ba796a0f324193fc6f69194-run_1/status
The job is done and is being held in memory.
4
http://localhost:1234/api/v1/memory/bfb440ab3ba796a0f324193fc6f69194-run_1/plot

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-4522388b8c8e> in <module>
      6     "localhost", port=1234)).with_model(model).run()
      7 results.wait()
----> 8 results.plot()

~/bs/computetest4/stochss-compute/stochss_compute/remote_results.py in hook_plot(self, *args, **kwargs)
     84 
     85         if plot_response.status_code == 404:
---> 86             raise Exception(plot_response.text)
     87 
     88         print(f"Plot size: {sys.getsizeof(plot_response.content)}")

Exception: The job is done and is being held in memory.

```

**Comment by mdip226** [comment]
I'm guessing that is what you just mentioned

**Comment by mdip226** [comment]
> @mdip226 When you run this make sure a directory is created where you spawned the Dask Cluster. It should contain file names with long MD5 hashes.

This one?
/home/mdip/dask-worker-space/worker-wha_4j3h/storage

**Comment by ethangreen-dev** [comment]
We're fighting Dask local dependencies again -- I can't run `SimpleDiskCache#put` without Dask having stochss-compute as a local dependency. Nasty stuff, we'll need to fix it later down the line.

Anyways, this fixes the disk cache no functioning correctly. All completed jobs should be stored within the `sd-cache` directory wherever you started your Dask workers.

**Comment by mdip226** [comment]
> We're fighting Dask local dependencies again -- I can't run `SimpleDiskCache#put` without Dask having stochss-compute as a local dependency. Nasty stuff, we'll need to fix it later down the line.
> 
> Anyways, this fixes the disk cache not functioning correctly. All completed jobs should be stored within the `sd-cache` directory wherever you started your Dask workers.

ok, I found the directory, but it placed it in the main repo directory, even though I started my worker in ~

**Comment by mdip226** [comment]
all is well again

**Review by mdip226 — APPROVED** [review]
it ran! :) files look good too

**Pull request merged**
